Add files via upload

diff --git a/tailscale-regress b/tailscale-regress
--- a/tailscale-regress
+++ b/tailscale-regress
@@ -1,4 +1,58 @@
 #!/bin/sh
+SCRIPT="$(basename $0)"
+
+usage() {
+cat <<EOH
+
+Usage: $0 [options]
+
+Options:
+ -U  Download the latest version of $SCRIPT from GitHub
+
+EOH
+exit
+}
+
+upgrade() {
+  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/UncleSam1966/tch-tailscale/master/$SCRIPT)
+  if [ "$RESPONSE_CODE" = 200 ];then
+    curl -kL -o $SCRIPT https://raw.githubusercontent.com/UncleSam1966/tch-tailscale/master/$SCRIPT
+    if [ $? -eq 0 ];then
+      chmod +x $SCRIPT
+      echo "[Tailscale-Install] Successfully downloaded $SCRIPT."
+    else
+      echo "[Tailscale-Install] Failed to download $SCRIPT."
+    fi
+  elif [ "$RESPONSE_CODE" = 404 ];then
+    echo "[Tailscale-Install] ERROR! Not found on GitHub???"
+  elif [ "$RESPONSE_CODE" = 000 ];then
+    echo "ERROR! No Internet connection???"
+  else
+    echo "[Tailscale-Install] ERROR! Unknown response code $RESPONSE_CODE"
+  fi
+  exit
+}
+
+while getopts :U option; do
+ case "${option}" in
+  U)  upgrade;;
+  *)  usage;;
+ esac
+done
+shift $((OPTIND-1))
+
+echo 
+echo "Installs the previous release of Tailscale."
+echo 
+echo "If you wish to proceed, enter y otherwise just press [Enter] to stop: "
+echo 
+read REPLY
+if [ "$REPLY" != "y" -a "$REPLY" != "Y" ]; then
+#  rm ./runonce
+      echo "[Tailscale-Install] Regression aborted."
+	  echo 
+  exit
+fi
 
 # check the version of the installed Tailscale
 echo "[Tailscale-Update] Getting installed Tailscale version..."
